CREATE DATABASE EVENT_STREAM_LIBRARY
USE DATABASE EVENT_STREAM_LIBRARY;

CREATE SCHEMA RAW;
USE SCHEMA RAW;

CREATE STORAGE INTEGRATION AWS_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::SnowflakeRole'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<path>')

DESC INTEGRATION AWS_S3_INTEGRATION

CREATE OR REPLACE FILE FORMAT CSV_ONLINE_LIBRARY
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  ENCODING = 'UTF8';

CREATE OR REPLACE STAGE AWS_ONLINE_LIBRARY_EVENTS
  STORAGE_INTEGRATION = AWS_S3_INTEGRATION
  URL = 's3://<path>'
  FILE_FORMAT = 'CSV_ONLINE_LIBRARY';

CREATE OR REPLACE TABLE ONLINE_LIBRARY_EVENTS (
  event_id         STRING,
  event_timestamp  TIMESTAMP_NTZ,
  event_type       STRING,
  user_id          STRING,
  book_id          STRING,
  session_id       STRING,
  event_metadata   VARIANT
);

COPY INTO
    ONLINE_LIBRARY_EVENTS (event_id, event_timestamp, event_type, user_id, book_id, session_id, event_metadata)
FROM (
  SELECT
    $1::STRING,
    TO_TIMESTAMP_NTZ($2),
    $3::STRING,
    $4::STRING,
    $5::STRING,
    $6::STRING,
    TRY_PARSE_JSON($7)
  FROM
    @AWS_ONLINE_LIBRARY_EVENTS
);
