USE DATABASE EVENT_STREAM_LIBRARY;
USE SCHEMA RAW;

CREATE STORAGE INTEGRATION GCP_GCS_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'GCS'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('gcs://<path>')

DESC INTEGRATION GCP_GCS_INTEGRATION;

CREATE STAGE GCS_ONLINE_LIBRARY_EVENTS
  URL = 'gcs://<path>'
  STORAGE_INTEGRATION = GCP_GCS_INTEGRATION
  FILE_FORMAT = CSV_ONLINE_LIBRARY;

COPY INTO @GCS_ONLINE_LIBRARY_EVENTS
FROM ONLINE_LIBRARY_EVENTS;
